basePath: /
definitions:
  models.Account:
    properties:
      create_at:
        type: string
      delete_at:
        type: string
      email:
        type: string
      id:
        type: integer
      uid:
        type: string
      update_at:
        type: string
      username:
        type: string
    type: object
  models.Impression:
    properties:
      body:
        type: string
      bookid:
        type: string
      booktitle:
        type: string
      create_at:
        type: string
      delete_at:
        type: string
      id:
        type: integer
      imageurl:
        type: string
      isbn10:
        type: string
      isbn13:
        type: string
      title:
        type: string
      uid:
        type: string
      update_at:
        type: string
    type: object
host: Secret
info:
  contact: {}
  description: API of software to describe impressions of books.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: book_Impressions_back
  version: 1.0.0
paths:
  /api/account/login:
    post:
      consumes:
      - application/json
      description: JWT certification
      produces:
      - application/json
      responses:
        "200":
          description: 200 OK
          schema:
            type: string
        "400":
          description: 400 incrrect password
          schema:
            type: string
        "401":
          description: 401 unauthenticated
          schema:
            type: string
        "404":
          description: 404 Not Found
          schema:
            type: string
      summary: If the infomation passed in the request body matches the data in the
        table, a cookie will be issued.
      tags:
      - account
  /api/account/logout:
    post:
      consumes:
      - application/json
      description: JWT certification
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "401":
          description: 401 unauthenticated
          schema:
            type: string
      summary: If the cookie exists, delete it.
      tags:
      - account
  /api/account/nowuser:
    delete:
      consumes:
      - application/json
      description: Browse Account table.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Account'
        "401":
          description: 401 unauthenticated
          schema:
            type: string
        "404":
          description: 404 Not Found
          schema:
            type: string
      summary: Deletes infomation about the currently logged in user.
      tags:
      - account
    get:
      consumes:
      - application/json
      description: Browse Account table.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Account'
        "401":
          description: 401 unauthenticated
          schema:
            type: string
      summary: Show infomation about the currently logged in user.
      tags:
      - account
    put:
      consumes:
      - application/json
      description: Browse Account table.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Account'
        "401":
          description: 401 unauthenticated
          schema:
            type: string
        "404":
          description: 404 Not Found
          schema:
            type: string
      summary: Updates information about the currently logged in user.
      tags:
      - account
  /api/account/signup:
    post:
      consumes:
      - application/json
      description: Use the account table.
      produces:
      - application/json
      responses:
        "201":
          description: 201 Created
          schema:
            type: string
        "409":
          description: 409 It is already registered
          schema:
            type: string
      summary: Register Account infomation in the database.
      tags:
      - account
  /api/impression/:id:
    delete:
      consumes:
      - application/json
      description: Can be executed only at login.
      produces:
      - application/json
      responses:
        "200":
          description: 200 OK
          schema:
            type: string
        "401":
          description: 401 unauthenticated
          schema:
            type: string
        "404":
          description: 404 Not Found
          schema:
            type: string
      summary: Delete impressions.
      tags:
      - impression
    get:
      consumes:
      - application/json
      description: Can be executed only at login.
      produces:
      - application/json
      responses:
        "200":
          description: 200 OK
          schema:
            type: string
        "401":
          description: 401 unauthenticated
          schema:
            type: string
        "404":
          description: 404 Not Found
          schema:
            type: string
      summary: Display of impressions.
      tags:
      - impression
    put:
      consumes:
      - application/json
      description: Can be executed only at login.
      produces:
      - application/json
      responses:
        "200":
          description: 200 OK
          schema:
            type: string
        "401":
          description: 401 unauthenticated
          schema:
            type: string
        "404":
          description: 404 Not Found
          schema:
            type: string
      summary: Update of impressions.
      tags:
      - impression
  /api/impressions:
    get:
      consumes:
      - application/json
      description: Can be executed only at login.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Impression'
        "401":
          description: 401 unauthenticated
          schema:
            type: string
      summary: List of impressions
      tags:
      - impressions
    post:
      consumes:
      - application/json
      description: Can be executed only at login.
      produces:
      - application/json
      responses:
        "200":
          description: 200 OK
          schema:
            type: string
        "401":
          description: 401 unauthenticated
          schema:
            type: string
      summary: impression registration process.
      tags:
      - impressions
  /api/impressions/search/:bookid:
    get:
      consumes:
      - application/json
      description: Can be executed only at login.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Impression'
        "401":
          description: 401 unauthenticated
          schema:
            type: string
        "404":
          description: 404 Not Found
          schema:
            type: string
      summary: Search for books using Bookid as a key.
      tags:
      - impressions
swagger: "2.0"
