version: "3"
services:
  https-portal3000:
    image: steveltn/https-portal:1
    ports:
      - "8083:443"
    environment:
      STAGE: local
      DOMAINS: "localhost -> http://api:8082"
  api:
    build:
      context: .
      dockerfile: ./.docker/api/Dockerfile
    tty: true
    ports:
      - "8082:8082"
    volumes:
      - ./api:/go/src/api
    command: go run main.go
